name: Laravel CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    steps:
      # 1. Thiết lập PHP
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: mbstring, bcmath, sqlite
          ini-values: post_max_size=256M, upload_max_filesize=256M

      # 2. Clone repository
      - name: Check out code
        uses: actions/checkout@v4

      # 3. Copy file .env
      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"
      - name: update packge
        run: composer update
      # 4. Install Composer dependencies
      - name: Install dependencies
        run: composer install --no-ansi --no-interaction --prefer-dist --no-progress

      # 5. Generate application key
      - name: Generate app key
        run: php artisan key:generate

      # 6. Set permissions
      - name: Set directory permissions
        run: chmod -R 777 storage bootstrap/cache

      # 7. Set up SQLite database
      - name: Set up database
        run: |
          mkdir -p database
          touch database/database.sqlite

      # 8. Run migrations and seed database
      - name: Run migrations and seeders
        env:
          DB_CONNECTION: sqlite
          DB_DATABASE: database/database.sqlite
        run: |
          php artisan migrate --force
          php artisan db:seed --force

      # 9. Run tests
      - name: Run tests
        env:
          DB_CONNECTION: sqlite
          DB_DATABASE: database/database.sqlite
        run: php artisan test
